# Generated by Django 5.2.8 on 2025-12-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
