# Generated by Django 5.2.8 on 2025-12-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sla_hours',
            field=models.FloatField(default=0.1667),
        ),
    ]
