# Generated by Django 5.2.8 on 2025-12-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sla_hours',
            field=models.FloatField(default=24),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Resolved - Pending Approval', 'Resolved - Pending Approval'), ('Closed', 'Closed'), ('Reopened', 'Reopened'), ('Escalated', 'Escalated')], default='Pending', max_length=50),
        ),
    ]
