# Generated by Django 5.2.8 on 2025-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_remove_userprofile_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Payroll', 'Payroll'), ('IT', 'IT'), ('Facilities', 'Facilities'), ('Security', 'Security'), ('Admin Dept', 'Admin Dept')], max_length=20, null=True),
        ),
    ]
